In [1]:
import pandas as pd
stations=pd.read_csv("C:/Users/prathik/Documents/Data Science Super Specialization/Tableau/Project/hubway_stations.csv")

In [2]:
trips=pd.read_csv("C:/Users/prathik/Documents/Data Science Super Specialization/Tableau/Project/hubway_trips.csv")

In [3]:
trips.head()

,seq_id,hubway_id,status,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,zip_code,birth_date,gender
0,1,8,Closed,9,7/28/2011 10:12:00,23.0,7/28/2011 10:12:00,23.0,B00468,Registered,'97217,1976.0,Male
1,2,9,Closed,220,7/28/2011 10:21:00,23.0,7/28/2011 10:25:00,23.0,B00554,Registered,'02215,1966.0,Male
2,3,10,Closed,56,7/28/2011 10:33:00,23.0,7/28/2011 10:34:00,23.0,B00456,Registered,'02108,1943.0,Male
3,4,11,Closed,64,7/28/2011 10:35:00,23.0,7/28/2011 10:36:00,23.0,B00554,Registered,'02116,1981.0,Female
4,5,12,Closed,12,7/28/2011 10:37:00,23.0,7/28/2011 10:37:00,23.0,B00554,Registered,'97214,1983.0,Female

In [4]:
result=trips

In [5]:
unique_values=[]
for n in range(1,146):
    df=result.loc[result['end_statn'] == n]
    df=df.drop_duplicates(subset='strt_statn', keep='first', inplace=False)
    unique_values.append(df)
unique_values=pd.concat(unique_values)

In [6]:
result = pd.merge(unique_values,
                 stations,
                 left_on='strt_statn',right_on='id')
result['origin_destination']='origin'

In [7]:
result.head(2)

,seq_id,hubway_id,status_x,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,...,birth_date,gender,id,terminal,station,municipal,lat,lng,status_y,origin_destination
0,62,85,Closed,50,7/28/2011 12:31:00,3,7/28/2011 12:32:00,3.0,B00071,Registered,...,1967.0,Male,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing,origin
1,37799,41778,Closed,822,8/30/2011 20:32:00,3,8/30/2011 20:46:00,4.0,B00269,Registered,...,1976.0,Male,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing,origin

In [8]:
result_1 = pd.merge(unique_values,
                 stations,
                 left_on='end_statn',right_on='id')
result_1['origin_destination']='destination'
result_1.head()

,seq_id,hubway_id,status_x,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,...,birth_date,gender,id,terminal,station,municipal,lat,lng,status_y,origin_destination
0,62,85,Closed,50,7/28/2011 12:31:00,3.0,7/28/2011 12:32:00,3,B00071,Registered,...,1967.0,Male,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing,destination
1,383,431,Closed,803,7/28/2011 22:02:00,42.0,7/28/2011 22:16:00,3,B00457,Registered,...,1986.0,Male,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing,destination
2,611,682,Closed,395,7/29/2011 13:01:00,32.0,7/29/2011 13:07:00,3,B00131,Casual,...,NaN,NaN,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing,destination
3,1204,1338,Closed,1340,7/30/2011 13:39:00,21.0,7/30/2011 14:01:00,3,B00486,Registered,...,1976.0,Female,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing,destination
4,1216,1353,Closed,1871,7/30/2011 13:47:00,6.0,7/30/2011 14:19:00,3,B00488,Casual,...,NaN,NaN,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing,destination

In [9]:
final = pd.concat([result, result_1])

In [10]:
final.head(2)

,seq_id,hubway_id,status_x,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,...,birth_date,gender,id,terminal,station,municipal,lat,lng,status_y,origin_destination
0,62,85,Closed,50,7/28/2011 12:31:00,3,7/28/2011 12:32:00,3,B00071,Registered,...,1967.0,Male,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing,origin
1,37799,41778,Closed,822,8/30/2011 20:32:00,3,8/30/2011 20:46:00,4,B00269,Registered,...,1976.0,Male,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing,origin

In [11]:
final.sort_values(by='seq_id')

,seq_id,hubway_id,status_x,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,...,birth_date,gender,id,terminal,station,municipal,lat,lng,status_y,origin_destination
3747,1,8,Closed,9,7/28/2011 10:12:00,23,7/28/2011 10:12:00,23,B00468,Registered,...,1976.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
2468,1,8,Closed,9,7/28/2011 10:12:00,23,7/28/2011 10:12:00,23,B00468,Registered,...,1976.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
6260,10,17,Closed,1108,7/28/2011 11:55:00,47,7/28/2011 12:13:00,40,B00550,Registered,...,1994.0,Male,47,D32010,Cross St. at Hanover St.,Boston,42.362811,-71.056067,Existing,origin
4306,10,17,Closed,1108,7/28/2011 11:55:00,47,7/28/2011 12:13:00,40,B00550,Registered,...,1994.0,Male,40,D32006,Lewis Wharf - Atlantic Ave.,Boston,42.363871,-71.050877,Existing,destination
5218,13,23,Closed,994,7/28/2011 12:00:00,40,7/28/2011 12:16:00,47,B00368,Casual,...,NaN,NaN,47,D32010,Cross St. at Hanover St.,Boston,42.362811,-71.056067,Existing,destination
3054,13,23,Closed,994,7/28/2011 12:00:00,40,7/28/2011 12:16:00,47,B00368,Casual,...,NaN,NaN,40,D32006,Lewis Wharf - Atlantic Ave.,Boston,42.363871,-71.050877,Existing,origin
943,14,25,Closed,15,7/28/2011 12:00:00,22,7/28/2011 12:00:00,22,B00442,Registered,...,1982.0,Male,22,A32010,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547,Existing,origin
2336,14,25,Closed,15,7/28/2011 12:00:00,22,7/28/2011 12:00:00,22,B00442,Registered,...,1982.0,Male,22,A32010,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547,Existing,destination
3032,15,27,Closed,952,7/28/2011 12:00:00,40,7/28/2011 12:16:00,23,B00556,Registered,...,1944.0,Male,40,D32006,Lewis Wharf - Atlantic Ave.,Boston,42.363871,-71.050877,Existing,origin
2469,15,27,Closed,952,7/28/2011 12:00:00,40,7/28/2011 12:16:00,23,B00556,Registered,...,1944.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
965,17,29,Closed,1261,7/28/2011 12:00:00,22,7/28/2011 12:21:00,45,B00454,Registered,...,1975.0,Male,22,A32010,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547,Existing,origin
4945,17,29,Closed,1261,7/28/2011 12:00:00,22,7/28/2011 12:21:00,45,B00454,Registered,...,1975.0,Male,45,B32011,Yawkey Way at Boylston St.,Boston,42.344763,-71.097880,Existing,destination
4224,19,31,Closed,1020,7/28/2011 12:01:00,38,7/28/2011 12:18:00,36,B00147,Registered,...,1987.0,Female,38,D32003,TD Garden - Legends Way,Boston,42.366231,-71.060868,Removed,origin
3875,19,31,Closed,1020,7/28/2011 12:01:00,38,7/28/2011 12:18:00,36,B00147,Registered,...,1987.0,Female,36,D32005,Boston Public Library - 700 Boylston St.,Boston,42.349673,-71.077303,Existing,destination
4232,20,33,Closed,1264,7/28/2011 12:01:00,38,7/28/2011 12:22:00,44,B00165,Registered,...,1985.0,Female,38,D32003,TD Garden - Legends Way,Boston,42.366231,-71.060868,Removed,origin
4810,20,33,Closed,1264,7/28/2011 12:01:00,38,7/28/2011 12:22:00,44,B00165,Registered,...,1985.0,Female,44,D32009,Faneuil Hall - Union St. at North St.,Boston,42.360583,-71.056868,Existing,destination
964,22,35,Closed,969,7/28/2011 12:01:00,22,7/28/2011 12:17:00,44,B00487,Registered,...,1971.0,Male,22,A32010,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547,Existing,origin
4811,22,35,Closed,969,7/28/2011 12:01:00,22,7/28/2011 12:17:00,44,B00487,Registered,...,1971.0,Male,44,D32009,Faneuil Hall - Union St. at North St.,Boston,42.360583,-71.056868,Existing,destination
4199,23,37,Closed,1582,7/28/2011 12:01:00,38,7/28/2011 12:27:00,10,B00093,Registered,...,1980.0,Female,38,D32003,TD Garden - Legends Way,Boston,42.366231,-71.060868,Removed,origin
877,23,37,Closed,1582,7/28/2011 12:01:00,38,7/28/2011 12:27:00,10,B00093,Registered,...,1980.0,Female,10,A32003,B.U. Central - 725 Comm. Ave.,Boston,42.350075,-71.105884,Existing,destination
2074,24,38,Closed,620,7/28/2011 12:01:00,22,7/28/2011 12:12:00,20,B00375,Registered,...,1955.0,Female,20,B32004,Aquarium Station - 200 Atlantic Ave.,Boston,42.359770,-71.051601,Existing,destination
941,24,38,Closed,620,7/28/2011 12:01:00,22,7/28/2011 12:12:00,20,B00375,Registered,...,1955.0,Female,22,A32010,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547,Existing,origin
4230,26,41,Closed,771,7/28/2011 12:02:00,38,7/28/2011 12:15:00,42,B00279,Registered,...,1943.0,Male,38,D32003,TD Garden - Legends Way,Boston,42.366231,-71.060868,Removed,origin
4554,26,41,Closed,771,7/28/2011 12:02:00,38,7/28/2011 12:15:00,42,B00279,Registered,...,1943.0,Male,42,D32007,Boylston St. at Arlington St.,Boston,42.352096,-71.070378,Existing,destination
4086,30,45,Closed,824,7/28/2011 12:02:00,22,7/28/2011 12:16:00,38,B00460,Registered,...,1967.0,Male,38,D32003,TD Garden - Legends Way,Boston,42.366231,-71.060868,Removed,destination
958,30,45,Closed,824,7/28/2011 12:02:00,22,7/28/2011 12:16:00,38,B00460,Registered,...,1967.0,Male,22,A32010,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547,Existing,origin
4235,31,47,Closed,873,7/28/2011 12:02:00,38,7/28/2011 12:17:00,47,B00025,Registered,...,1975.0,Female,38,D32003,TD Garden - Legends Way,Boston,42.366231,-71.060868,Removed,origin
5219,31,47,Closed,873,7/28/2011 12:02:00,38,7/28/2011 12:17:00,47,B00025,Registered,...,1975.0,Female,47,D32010,Cross St. at Hanover St.,Boston,42.362811,-71.056067,Existing,destination
946,32,48,Closed,1377,7/28/2011 12:03:00,22,7/28/2011 12:26:00,25,B00404,Registered,...,1982.0,Male,22,A32010,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547,Existing,origin
2675,32,48,Closed,1377,7/28/2011 12:03:00,22,7/28/2011 12:26:00,25,B00404,Registered,...,1982.0,Male,25,A32009,Tremont St / W Newton St,Boston,42.341332,-71.076847,Existing,destination
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12533,1573575,1742326,Closed,2160,11/23/2013 12:24:00,126,11/23/2013 13:00:00,123,T01083,Registered,...,NaN,Female,126,K32002,Washington Square at Washington St. / Beacon St.,Brookline,42.339335,-71.134930,Existing,origin
13234,1573575,1742326,Closed,2160,11/23/2013 12:24:00,126,11/23/2013 13:00:00,123,T01083,Registered,...,NaN,Female,123,E32004,Egleston Square at Columbus Ave,Boston,42.315692,-71.098634,Existing,destination
11328,1573766,1742528,Closed,2220,11/23/2013 13:45:00,92,11/23/2013 14:22:00,99,B01490,Casual,...,NaN,NaN,99,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.358920,-71.057629,Existing,destination
14435,1573766,1742528,Closed,2220,11/23/2013 13:45:00,92,11/23/2013 14:22:00,99,B01490,Casual,...,NaN,NaN,92,C32014,University of Massachusetts Boston,Boston,42.311819,-71.035705,Existing,origin
13018,1573824,1742586,Closed,1080,11/23/2013 14:11:00,7,11/23/2013 14:29:00,119,T01331,Registered,...,NaN,Male,119,D32027,New Balance Store - Boylston at Dartmouth,Boston,42.350413,-71.076550,Existing,destination
12873,1573824,1742586,Closed,1080,11/23/2013 14:11:00,7,11/23/2013 14:29:00,119,T01331,Registered,...,NaN,Male,7,A32000,Fan Pier,Boston,42.353412,-71.044624,Existing,origin
11496,1573931,1742696,Closed,1020,11/23/2013 15:08:00,135,11/23/2013 15:25:00,101,b00225,Registered,...,NaN,Male,101,B32020,BIDMC - Brookline at Burlington St,Boston,42.345733,-71.100694,Existing,destination
13587,1573931,1742696,Closed,1020,11/23/2013 15:08:00,135,11/23/2013 15:25:00,101,b00225,Registered,...,NaN,Male,135,M32026,359 Broadway - Broadway at Fayette Street,Cambridge,42.370803,-71.104412,Existing,origin
13019,1574464,1743252,Closed,240,11/23/2013 21:15:00,4,11/23/2013 21:19:00,119,T01335,Registered,...,NaN,Male,119,D32027,New Balance Store - Boylston at Dartmouth,Boston,42.350413,-71.076550,Existing,destination
4729,1574464,1743252,Closed,240,11/23/2013 21:15:00,4,11/23/2013 21:19:00,119,T01335,Registered,...,NaN,Male,4,C32000,Tremont St. at Berkeley St.,Boston,42.345392,-71.069616,Existing,origin
2763,1574611,1743409,Closed,1320,11/24/2013 00:49:00,46,11/24/2013 01:11:00,123,T01422,Casual,...,NaN,NaN,46,B32005,Christian Science Plaza,Boston,42.343864,-71.085918,Existing,origin
13235,1574611,1743409,Closed,1320,11/24/2013 00:49:00,46,11/24/2013 01:11:00,123,T01422,Casual,...,NaN,NaN,123,E32004,Egleston Square at Columbus Ave,Boston,42.315692,-71.098634,Existing,destination
15052,1574654,1743458,Closed,1800,11/24/2013 02:04:00,58,11/24/2013 02:34:00,142,T01046,Registered,...,NaN,Male,142,S32009,Packard Ave / Powderhouse Blvd,Somerville,42.404490,-71.123413,Existing,destination
6482,1574654,1743458,Closed,1800,11/24/2013 02:04:00,58,11/24/2013 02:34:00,142,T01046,Registered,...,NaN,Male,58,D32017,The Esplanade - Beacon St. at Arlington St.,Boston,42.355596,-71.072780,Existing,origin
13254,1575127,1743958,Closed,1620,11/24/2013 17:51:00,136,11/24/2013 18:18:00,69,T01085,Registered,...,NaN,Male,136,M32027,Biogen Idec - Binney St / Sixth St,Cambridge,42.366095,-71.086388,Existing,origin
8003,1575127,1743958,Closed,1620,11/24/2013 17:51:00,136,11/24/2013 18:18:00,69,T01085,Registered,...,NaN,Male,69,K32001,Coolidge Corner - Beacon St @ Centre St,Brookline,42.341598,-71.123338,Existing,destination
5852,1576185,1745071,Closed,1020,11/25/2013 17:23:00,63,11/25/2013 17:40:00,119,B00638,Casual,...,NaN,NaN,63,C32009,Dorchester Ave. at Gillette Park,Boston,42.344023,-71.057054,Existing,origin
13020,1576185,1745071,Closed,1020,11/25/2013 17:23:00,63,11/25/2013 17:40:00,119,B00638,Casual,...,NaN,NaN,119,D32027,New Balance Store - Boylston at Dartmouth,Boston,42.350413,-71.076550,Existing,destination
7252,1576328,1745221,Closed,780,11/25/2013 18:20:00,119,11/25/2013 18:33:00,63,B00491,Registered,...,NaN,Male,63,C32009,Dorchester Ave. at Gillette Park,Boston,42.344023,-71.057054,Existing,destination
14243,1576328,1745221,Closed,780,11/25/2013 18:20:00,119,11/25/2013 18:33:00,63,B00491,Registered,...,NaN,Male,119,D32027,New Balance Store - Boylston at Dartmouth,Boston,42.350413,-71.076550,Existing,origin
13021,1576684,1745591,Closed,1560,11/26/2013 07:16:00,114,11/26/2013 07:42:00,119,T01279,Registered,...,NaN,Male,119,D32027,New Balance Store - Boylston at Dartmouth,Boston,42.350413,-71.076550,Existing,destination
11583,1576684,1745591,Closed,1560,11/26/2013 07:16:00,114,11/26/2013 07:42:00,119,T01279,Registered,...,NaN,Male,114,D32022,TD Garden - Causeway at Portal Park #1,Boston,42.365942,-71.060515,Existing,origin
14021,1577350,1746281,Closed,1020,11/26/2013 13:57:00,119,11/26/2013 14:14:00,131,B00429,Registered,...,NaN,Male,131,M32022,Lower Cambridgeport at Magazine St/Riverside Rd,Cambridge,42.356954,-71.113687,Existing,destination
14272,1577350,1746281,Closed,1020,11/26/2013 13:57:00,119,11/26/2013 14:14:00,131,B00429,Registered,...,NaN,Male,119,D32027,New Balance Store - Boylston at Dartmouth,Boston,42.350413,-71.076550,Existing,origin
14256,1577764,1746703,Closed,960,11/26/2013 17:55:00,119,11/26/2013 18:11:00,96,T01075,Registered,...,NaN,Male,119,D32027,New Balance Store - Boylston at Dartmouth,Boston,42.350413,-71.076550,Existing,origin
11034,1577764,1746703,Closed,960,11/26/2013 17:55:00,119,11/26/2013 18:11:00,96,T01075,Registered,...,NaN,Male,96,M32013,Cambridge Main Library at Broadway / Trowbridg...,Cambridge,42.373379,-71.111075,Existing,destination
12071,1578137,1747091,Closed,1200,11/27/2013 13:37:00,127,11/27/2013 13:57:00,88,A07800,Registered,...,NaN,Male,127,K32004,JFK Crossing at Harvard St. / Thorndike St.,Brookline,42.346563,-71.128374,Existing,origin
10168,1578137,1747091,Closed,1200,11/27/2013 13:37:00,127,11/27/2013 13:57:00,88,A07800,Registered,...,NaN,Male,88,M32010,Inman Square at Vellucci Plaza / Hampshire St,Cambridge,42.374035,-71.101427,Existing,destination
13236,1578340,1747320,Closed,2100,11/27/2013 22:27:00,36,11/27/2013 23:02:00,123,B00147,Registered,...,NaN,Male,123,E32004,Egleston Square at Columbus Ave,Boston,42.315692,-71.098634,Existing,destination
2623,1578340,1747320,Closed,2100,11/27/2013 22:27:00,36,11/27/2013 23:02:00,123,B00147,Registered,...,NaN,Male,36,D32005,Boston Public Library - 700 Boylston St.,Boston,42.349673,-71.077303,Existing,origin

In [12]:
list=final.columns.tolist()
drop_cols=['hubway_id', 'status_x', 'duration','start_date','end_date','bike_nr','subsc_type',
 'zip_code', 'birth_date', 'gender','municipal','status_y']

In [13]:
final=final.drop(drop_cols,axis=1)

In [14]:
final.head(2)

,seq_id,strt_statn,end_statn,id,terminal,station,lat,lng,origin_destination
0,62,3,3,3,B32006,Colleges of the Fenway,42.340021,-71.100812,origin
1,37799,3,4,3,B32006,Colleges of the Fenway,42.340021,-71.100812,origin

In [15]:
final.sort_values(by='seq_id').head(2)

,seq_id,strt_statn,end_statn,id,terminal,station,lat,lng,origin_destination
3747,1,23,23,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,origin
2468,1,23,23,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,destination

In [16]:
bike_data=final.drop(['strt_statn','end_statn'],axis=1)

In [17]:
bike_data.head(2)

,seq_id,id,terminal,station,lat,lng,origin_destination
0,62,3,B32006,Colleges of the Fenway,42.340021,-71.100812,origin
1,37799,3,B32006,Colleges of the Fenway,42.340021,-71.100812,origin

In [18]:
bike_data.to_csv("C:/Users/prathik/Documents/Data Science Super Specialization/Tableau/Project/bike_data_unique_end.csv")

In [25]:
'''def origin_station (row):
   if row['origin_destination'] == 'origin' :
      return bike_data.station'''

In [ ]:
#bike_data.apply (lambda row: origin_station(row),axis=1)

In [18]:
'''origin_station=[]
for n in bike_data.origin_destination:
    if['origin_destination']=='origin':
        bike_data['origin_station']=bike_data.station'''

In [19]:
'''destination_station=[]
for n in bike_data.origin_destination:
    if['origin_destination']=='destination':
        bike_data['destination_station']=bike_data.station'''

In [20]:
#bike_data.columns

Index(['seq_id', 'id', 'terminal', 'station', 'lat', 'lng',
       'origin_destination'],
      dtype='object')

In [21]:
#bike_data.head(2)

,seq_id,id,terminal,station,lat,lng,origin_destination
0,1,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,origin
1,2,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,origin

In [22]:
#bike_data['origin_station']

KeyError: 'origin_station'