In [1]:
import pandas as pd
stations=pd.read_csv("C:/Users/prathik/Documents/Data Science Super Specialization/Tableau/Project/hubway_stations.csv")

In [2]:
trips=pd.read_csv("C:/Users/prathik/Documents/Data Science Super Specialization/Tableau/Project/hubway_trips.csv")

In [3]:
trips.head()

,seq_id,hubway_id,status,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,zip_code,birth_date,gender
0,1,8,Closed,9,7/28/2011 10:12:00,23.0,7/28/2011 10:12:00,23.0,B00468,Registered,'97217,1976.0,Male
1,2,9,Closed,220,7/28/2011 10:21:00,23.0,7/28/2011 10:25:00,23.0,B00554,Registered,'02215,1966.0,Male
2,3,10,Closed,56,7/28/2011 10:33:00,23.0,7/28/2011 10:34:00,23.0,B00456,Registered,'02108,1943.0,Male
3,4,11,Closed,64,7/28/2011 10:35:00,23.0,7/28/2011 10:36:00,23.0,B00554,Registered,'02116,1981.0,Female
4,5,12,Closed,12,7/28/2011 10:37:00,23.0,7/28/2011 10:37:00,23.0,B00554,Registered,'97214,1983.0,Female

In [4]:
result = pd.merge(trips,
                 stations,
                 left_on='strt_statn',right_on='id')
result['origin_destination']='origin'

In [5]:
result.head(2)

,seq_id,hubway_id,status_x,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,...,birth_date,gender,id,terminal,station,municipal,lat,lng,status_y,origin_destination
0,1,8,Closed,9,7/28/2011 10:12:00,23,7/28/2011 10:12:00,23.0,B00468,Registered,...,1976.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
1,2,9,Closed,220,7/28/2011 10:21:00,23,7/28/2011 10:25:00,23.0,B00554,Registered,...,1966.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin

In [6]:
result_1 = pd.merge(trips,
                 stations,
                 left_on='end_statn',right_on='id')
result_1['origin_destination']='destination'

In [7]:
result_1.head(2)

,seq_id,hubway_id,status_x,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,...,birth_date,gender,id,terminal,station,municipal,lat,lng,status_y,origin_destination
0,1,8,Closed,9,7/28/2011 10:12:00,23.0,7/28/2011 10:12:00,23,B00468,Registered,...,1976.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
1,2,9,Closed,220,7/28/2011 10:21:00,23.0,7/28/2011 10:25:00,23,B00554,Registered,...,1966.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination

In [8]:
final = pd.concat([result, result_1])

In [9]:
final.head(2)

,seq_id,hubway_id,status_x,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,...,birth_date,gender,id,terminal,station,municipal,lat,lng,status_y,origin_destination
0,1,8,Closed,9,7/28/2011 10:12:00,23,7/28/2011 10:12:00,23,B00468,Registered,...,1976.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
1,2,9,Closed,220,7/28/2011 10:21:00,23,7/28/2011 10:25:00,23,B00554,Registered,...,1966.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin

In [10]:
final.sort_values(by='seq_id')

,seq_id,hubway_id,status_x,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,...,birth_date,gender,id,terminal,station,municipal,lat,lng,status_y,origin_destination
0,1,8,Closed,9,7/28/2011 10:12:00,23,7/28/2011 10:12:00,23,B00468,Registered,...,1976.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
0,1,8,Closed,9,7/28/2011 10:12:00,23,7/28/2011 10:12:00,23,B00468,Registered,...,1976.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
1,2,9,Closed,220,7/28/2011 10:21:00,23,7/28/2011 10:25:00,23,B00554,Registered,...,1966.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
1,2,9,Closed,220,7/28/2011 10:21:00,23,7/28/2011 10:25:00,23,B00554,Registered,...,1966.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
2,3,10,Closed,56,7/28/2011 10:33:00,23,7/28/2011 10:34:00,23,B00456,Registered,...,1943.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
2,3,10,Closed,56,7/28/2011 10:33:00,23,7/28/2011 10:34:00,23,B00456,Registered,...,1943.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
3,4,11,Closed,64,7/28/2011 10:35:00,23,7/28/2011 10:36:00,23,B00554,Registered,...,1981.0,Female,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
3,4,11,Closed,64,7/28/2011 10:35:00,23,7/28/2011 10:36:00,23,B00554,Registered,...,1981.0,Female,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
4,5,12,Closed,12,7/28/2011 10:37:00,23,7/28/2011 10:37:00,23,B00554,Registered,...,1983.0,Female,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
4,5,12,Closed,12,7/28/2011 10:37:00,23,7/28/2011 10:37:00,23,B00554,Registered,...,1983.0,Female,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
5,6,13,Closed,19,7/28/2011 10:39:00,23,7/28/2011 10:39:00,23,B00456,Registered,...,1951.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
5,6,13,Closed,19,7/28/2011 10:39:00,23,7/28/2011 10:39:00,23,B00456,Registered,...,1951.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
6,7,14,Closed,24,7/28/2011 10:47:00,23,7/28/2011 10:47:00,23,B00554,Registered,...,1971.0,Female,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
6,7,14,Closed,24,7/28/2011 10:47:00,23,7/28/2011 10:47:00,23,B00554,Registered,...,1971.0,Female,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
7,8,15,Closed,7,7/28/2011 10:48:00,23,7/28/2011 10:48:00,23,B00554,Registered,...,1971.0,Female,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
7,8,15,Closed,7,7/28/2011 10:48:00,23,7/28/2011 10:48:00,23,B00554,Registered,...,1971.0,Female,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
8,9,16,Closed,8,7/28/2011 11:01:00,23,7/28/2011 11:01:00,23,B00554,Registered,...,1983.0,Female,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,origin
8,9,16,Closed,8,7/28/2011 11:01:00,23,7/28/2011 11:01:00,23,B00554,Registered,...,1983.0,Female,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
11024,10,17,Closed,1108,7/28/2011 11:55:00,47,7/28/2011 12:13:00,40,B00550,Registered,...,1994.0,Male,47,D32010,Cross St. at Hanover St.,Boston,42.362811,-71.056067,Existing,origin
9843,10,17,Closed,1108,7/28/2011 11:55:00,47,7/28/2011 12:13:00,40,B00550,Registered,...,1994.0,Male,40,D32006,Lewis Wharf - Atlantic Ave.,Boston,42.363871,-71.050877,Existing,destination
11025,11,18,Closed,1055,7/28/2011 11:55:00,47,7/28/2011 12:13:00,40,B00580,Registered,...,1956.0,Male,47,D32010,Cross St. at Hanover St.,Boston,42.362811,-71.056067,Existing,origin
9844,11,18,Closed,1055,7/28/2011 11:55:00,47,7/28/2011 12:13:00,40,B00580,Registered,...,1956.0,Male,40,D32006,Lewis Wharf - Atlantic Ave.,Boston,42.363871,-71.050877,Existing,destination
11026,12,19,Closed,1042,7/28/2011 11:55:00,47,7/28/2011 12:12:00,40,B00539,Registered,...,1959.0,Female,47,D32010,Cross St. at Hanover St.,Boston,42.362811,-71.056067,Existing,origin
9845,12,19,Closed,1042,7/28/2011 11:55:00,47,7/28/2011 12:12:00,40,B00539,Registered,...,1959.0,Female,40,D32006,Lewis Wharf - Atlantic Ave.,Boston,42.363871,-71.050877,Existing,destination
34590,13,23,Closed,994,7/28/2011 12:00:00,40,7/28/2011 12:16:00,47,B00368,Casual,...,NaN,NaN,47,D32010,Cross St. at Hanover St.,Boston,42.362811,-71.056067,Existing,destination
37843,13,23,Closed,994,7/28/2011 12:00:00,40,7/28/2011 12:16:00,47,B00368,Casual,...,NaN,NaN,40,D32006,Lewis Wharf - Atlantic Ave.,Boston,42.363871,-71.050877,Existing,origin
63863,14,25,Closed,15,7/28/2011 12:00:00,22,7/28/2011 12:00:00,22,B00442,Registered,...,1982.0,Male,22,A32010,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547,Existing,origin
60245,14,25,Closed,15,7/28/2011 12:00:00,22,7/28/2011 12:00:00,22,B00442,Registered,...,1982.0,Male,22,A32010,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547,Existing,destination
37844,15,27,Closed,952,7/28/2011 12:00:00,40,7/28/2011 12:16:00,23,B00556,Registered,...,1944.0,Male,40,D32006,Lewis Wharf - Atlantic Ave.,Boston,42.363871,-71.050877,Existing,origin
9,15,27,Closed,952,7/28/2011 12:00:00,40,7/28/2011 12:16:00,23,B00556,Registered,...,1944.0,Male,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed,destination
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1161627,1579011,1748008,Closed,540,11/30/2013 21:55:00,76,11/30/2013 22:04:00,68,T01175,Registered,...,NaN,Male,68,M32011,Central Square at Mass Ave / Essex St,Cambridge,42.365070,-71.103100,Existing,destination
1084670,1579011,1748008,Closed,540,11/30/2013 21:55:00,76,11/30/2013 22:04:00,68,T01175,Registered,...,NaN,Male,76,M32012,Central Sq Post Office / Cambridge City Hall a...,Cambridge,42.366426,-71.105495,Existing,origin
1161628,1579012,1748009,Closed,1440,11/30/2013 22:15:00,130,11/30/2013 22:39:00,68,B01480,Registered,...,NaN,Male,68,M32011,Central Square at Mass Ave / Essex St,Cambridge,42.365070,-71.103100,Existing,destination
1549458,1579012,1748009,Closed,1440,11/30/2013 22:15:00,130,11/30/2013 22:39:00,68,B01480,Registered,...,NaN,Male,130,M32021,Harvard University Gund Hall at Quincy St / Ki...,Cambridge,42.376369,-71.114025,Existing,origin
1559942,1579013,1748010,Closed,480,11/30/2013 22:25:00,137,11/30/2013 22:33:00,74,T01308,Registered,...,NaN,Male,137,M32029,Porter Square Station,Cambridge,42.387995,-71.119084,Existing,origin
1110402,1579013,1748010,Closed,480,11/30/2013 22:25:00,137,11/30/2013 22:33:00,74,T01308,Registered,...,NaN,Male,74,M32018,Harvard Square at Mass Ave/ Dunster,Cambridge,42.373268,-71.118579,Existing,destination
1559943,1579014,1748011,Closed,420,11/30/2013 22:25:00,137,11/30/2013 22:32:00,74,T01043,Registered,...,NaN,Female,137,M32029,Porter Square Station,Cambridge,42.387995,-71.119084,Existing,origin
1110403,1579014,1748011,Closed,420,11/30/2013 22:25:00,137,11/30/2013 22:32:00,74,T01043,Registered,...,NaN,Female,74,M32018,Harvard Square at Mass Ave/ Dunster,Cambridge,42.373268,-71.118579,Existing,destination
1161629,1579015,1748012,Closed,360,11/30/2013 22:51:00,67,11/30/2013 22:57:00,68,T01352,Registered,...,NaN,Male,68,M32011,Central Square at Mass Ave / Essex St,Cambridge,42.365070,-71.103100,Existing,destination
1217805,1579015,1748012,Closed,360,11/30/2013 22:51:00,67,11/30/2013 22:57:00,68,T01352,Registered,...,NaN,Male,67,M32006,MIT at Mass Ave / Amherst St,Cambridge,42.358100,-71.093198,Existing,origin
1342738,1579016,1748013,Closed,300,11/30/2013 22:53:00,74,11/30/2013 22:58:00,87,T01217,Registered,...,NaN,Female,87,M32014,Harvard University Housing - 115 Putnam Ave at...,Cambridge,42.366621,-71.114214,Existing,destination
1108728,1579016,1748013,Closed,300,11/30/2013 22:53:00,74,11/30/2013 22:58:00,87,T01217,Registered,...,NaN,Female,74,M32018,Harvard Square at Mass Ave/ Dunster,Cambridge,42.373268,-71.118579,Existing,origin
1521364,1579017,1748014,Closed,120,11/30/2013 23:07:00,128,11/30/2013 23:09:00,136,B01468,Registered,...,NaN,Male,128,M32004,Kendall T at Main St,Cambridge,42.362457,-71.084970,Existing,origin
1572026,1579017,1748014,Closed,120,11/30/2013 23:07:00,128,11/30/2013 23:09:00,136,B01468,Registered,...,NaN,Male,136,M32027,Biogen Idec - Binney St / Sixth St,Cambridge,42.366095,-71.086388,Existing,destination
1376575,1579018,1748015,Closed,900,11/30/2013 23:17:00,76,11/30/2013 23:32:00,96,B00585,Registered,...,NaN,Female,96,M32013,Cambridge Main Library at Broadway / Trowbridg...,Cambridge,42.373379,-71.111075,Existing,destination
1084671,1579018,1748015,Closed,900,11/30/2013 23:17:00,76,11/30/2013 23:32:00,96,B00585,Registered,...,NaN,Female,76,M32012,Central Sq Post Office / Cambridge City Hall a...,Cambridge,42.366426,-71.105495,Existing,origin
1561899,1579019,1748016,Closed,240,11/30/2013 23:24:00,134,11/30/2013 23:28:00,139,T01195,Registered,...,NaN,Male,134,M32025,Mass Ave / Linear Park,Cambridge,42.397828,-71.130516,Existing,origin
1485503,1579019,1748016,Closed,240,11/30/2013 23:24:00,134,11/30/2013 23:28:00,139,T01195,Registered,...,NaN,Male,139,S32006,Davis Square,Somerville,42.396969,-71.123024,Existing,destination
1496726,1579020,1748017,Closed,360,11/30/2013 23:24:00,129,11/30/2013 23:30:00,133,T01069,Registered,...,NaN,Male,133,M32024,Harvard University Radcliffe Quadrangle at She...,Cambridge,42.380287,-71.125107,Existing,destination
1470226,1579020,1748017,Closed,360,11/30/2013 23:24:00,129,11/30/2013 23:30:00,133,T01069,Registered,...,NaN,Male,129,M32015,Harvard University River Houses / Plympton St ...,Cambridge,42.369832,-71.118201,Existing,origin
1336666,1579021,1748018,Closed,720,11/30/2013 23:30:00,130,11/30/2013 23:42:00,90,T01341,Registered,...,NaN,Male,90,M32001,Lechmere Station at Cambridge St / First St,Cambridge,42.370700,-71.077110,Existing,destination
1549459,1579021,1748018,Closed,720,11/30/2013 23:30:00,130,11/30/2013 23:42:00,90,T01341,Registered,...,NaN,Male,130,M32021,Harvard University Gund Hall at Quincy St / Ki...,Cambridge,42.376369,-71.114025,Existing,origin
1327851,1579022,1748019,Closed,480,11/30/2013 23:32:00,67,11/30/2013 23:40:00,88,T01328,Registered,...,NaN,Male,88,M32010,Inman Square at Vellucci Plaza / Hampshire St,Cambridge,42.374035,-71.101427,Existing,destination
1217806,1579022,1748019,Closed,480,11/30/2013 23:32:00,67,11/30/2013 23:40:00,88,T01328,Registered,...,NaN,Male,67,M32006,MIT at Mass Ave / Amherst St,Cambridge,42.358100,-71.093198,Existing,origin
1496727,1579023,1748020,Closed,540,11/30/2013 23:32:00,137,11/30/2013 23:41:00,133,T01310,Casual,...,NaN,NaN,133,M32024,Harvard University Radcliffe Quadrangle at She...,Cambridge,42.380287,-71.125107,Existing,destination
1559944,1579023,1748020,Closed,540,11/30/2013 23:32:00,137,11/30/2013 23:41:00,133,T01310,Casual,...,NaN,NaN,137,M32029,Porter Square Station,Cambridge,42.387995,-71.119084,Existing,origin
1161630,1579024,1748021,Closed,120,11/30/2013 23:36:00,76,11/30/2013 23:38:00,68,B01478,Registered,...,NaN,Male,68,M32011,Central Square at Mass Ave / Essex St,Cambridge,42.365070,-71.103100,Existing,destination
1084672,1579024,1748021,Closed,120,11/30/2013 23:36:00,76,11/30/2013 23:38:00,68,B01478,Registered,...,NaN,Male,76,M32012,Central Sq Post Office / Cambridge City Hall a...,Cambridge,42.366426,-71.105495,Existing,origin
1383944,1579025,1748022,Closed,420,11/30/2013 23:39:00,68,11/30/2013 23:46:00,95,T01352,Registered,...,NaN,Female,95,M32007,Cambridge St - at Columbia St / Webster Ave,Cambridge,42.372969,-71.094445,Existing,destination
1148718,1579025,1748022,Closed,420,11/30/2013 23:39:00,68,11/30/2013 23:46:00,95,T01352,Registered,...,NaN,Female,68,M32011,Central Square at Mass Ave / Essex St,Cambridge,42.365070,-71.103100,Existing,origin

In [11]:
list=final.columns.tolist()
drop_cols=['hubway_id', 'status_x', 'duration','start_date','end_date','bike_nr','subsc_type',
 'zip_code', 'birth_date', 'gender','municipal','status_y']

In [12]:
final=final.drop(drop_cols,axis=1)

In [13]:
final.head(2)

,seq_id,strt_statn,end_statn,id,terminal,station,lat,lng,origin_destination
0,1,23,23,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,origin
1,2,23,23,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,origin

In [14]:
final.sort_values(by='seq_id').head(2)

,seq_id,strt_statn,end_statn,id,terminal,station,lat,lng,origin_destination
0,1,23,23,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,origin
0,1,23,23,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,destination

In [15]:
bike_data=final.drop(['strt_statn','end_statn'],axis=1)

In [16]:
bike_data.head(2)

,seq_id,id,terminal,station,lat,lng,origin_destination
0,1,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,origin
1,2,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,origin

In [17]:
#bike_data.to_csv("C:/Users/prathik/Documents/Data Science Super Specialization/Tableau/Project/bike_data.csv")

In [25]:
def origin_station (row):
   if row['origin_destination'] == 'origin' :
      return bike_data.station

In [26]:
bike_data.apply (lambda row: origin_station(row),axis=1)

KeyboardInterrupt:

In [18]:
origin_station=[]
for n in bike_data.origin_destination:
    if['origin_destination']=='origin':
        bike_data['origin_station']=bike_data.station

In [19]:
destination_station=[]
for n in bike_data.origin_destination:
    if['origin_destination']=='destination':
        bike_data['destination_station']=bike_data.station

In [20]:
bike_data.columns

Index(['seq_id', 'id', 'terminal', 'station', 'lat', 'lng',
       'origin_destination'],
      dtype='object')

In [21]:
bike_data.head(2)

,seq_id,id,terminal,station,lat,lng,origin_destination
0,1,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,origin
1,2,23,B32008,Mayor Thomas M. Menino - Government Center,42.359677,-71.059364,origin

In [22]:
bike_data['origin_station']

KeyError: 'origin_station'